from typing import Protocol

from ..models import Newsletter, Post, Subscriber


class NewsletterRepository(Protocol):
    def get_newsletter(self, slug: str) -> Newsletter | None: ...

    def list_posts(self, newsletter_slug: str, published_only: bool = True) -> list[Post]: ...

    def get_post(self, newsletter_slug: str, post_slug: str) -> Post | None: ...

    def create_post(self, newsletter_slug: str, title: str, slug: str, body_md: str) -> Post: ...

    def update_post(self, post_id: int, title: str, slug: str, body_md: str) -> Post: ...

    def publish_post(self, post_id: int) -> Post: ...

    def mark_sent(self, post_id: int) -> None: ...

    def add_subscriber(self, newsletter_slug: str, email: str, token: str) -> Subscriber: ...

    def confirm_subscriber(self, token: str) -> Subscriber | None: ...

    def list_confirmed_subscribers(self, newsletter_slug: str) -> list[Subscriber]: ...

    def list_all_subscribers(self, newsletter_slug: str) -> list[Subscriber]: ...

    def unsubscribe(self, token: str) -> None: ...

    def create_newsletter(
        self, slug: str, name: str, from_email: str, from_name: str, reply_to: str | None
    ) -> Newsletter: ...
